/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    churches: Church;
    'landing-pages': LandingPage;
    ministries: Ministry;
    groups: Group;
    'group-memberships': GroupMembership;
    'group-sessions': GroupSession;
    'attendance-records': AttendanceRecord;
    courses: Course;
    'course-enrollments': CourseEnrollment;
    events: Event;
    sermons: Sermon;
    facilities: Facility;
    people: Person;
    contributions: Contribution;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    churches: ChurchesSelect<false> | ChurchesSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    ministries: MinistriesSelect<false> | MinistriesSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    'group-memberships': GroupMembershipsSelect<false> | GroupMembershipsSelect<true>;
    'group-sessions': GroupSessionsSelect<false> | GroupSessionsSelect<true>;
    'attendance-records': AttendanceRecordsSelect<false> | AttendanceRecordsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'course-enrollments': CourseEnrollmentsSelect<false> | CourseEnrollmentsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    sermons: SermonsSelect<false> | SermonsSelect<true>;
    facilities: FacilitiesSelect<false> | FacilitiesSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    contributions: ContributionsSelect<false> | ContributionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  roles: ('super-admin' | 'church-admin' | 'finance' | 'content-editor' | 'ministry-leader' | 'member')[];
  churches?: (number | Church)[] | null;
  person?: (number | null) | Person;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "churches".
 */
export interface Church {
  id: number;
  name: string;
  slug: string;
  status: 'draft' | 'published';
  tagline: string;
  summary: string;
  heroImage?: (number | null) | Media;
  serviceTimes?:
    | {
        label: string;
        day: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  address: {
    street: string;
    city: string;
    state: string;
    postalCode: string;
  };
  contact?: {
    phone?: string | null;
    email?: string | null;
    website?: string | null;
  };
  givingUrl?: string | null;
  livestreamUrl?: string | null;
  theme?: {
    preset?: ('warm' | 'calm' | 'bold') | null;
    accent?: string | null;
    surface?: string | null;
    ink?: string | null;
    heroTone?: ('warm' | 'calm' | 'bold') | null;
    radius?: ('soft' | 'rounded' | 'sharp') | null;
    headingFont?: ('serif-display' | 'modern-sans' | 'humanist-sans') | null;
    bodyFont?: ('classic-serif' | 'neutral-sans' | 'humanist-sans') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  church?: (number | null) | Church;
  resourceType?: ('image' | 'worksheet' | 'lesson-guide' | 'video' | 'handbook') | null;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  church: number | Church;
  firstName: string;
  lastName: string;
  email?: string | null;
  phone?: string | null;
  householdName?: string | null;
  membershipStatus?: ('guest' | 'regular-attender' | 'member' | 'volunteer') | null;
  volunteerReady?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  church: number | Church;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  pageType: 'ministry' | 'group' | 'course';
  ministry?: (number | null) | Ministry;
  group?: (number | null) | Group;
  course?: (number | null) | Course;
  themeMode: 'inherit' | 'custom';
  themeOverrides?: {
    accent?: string | null;
    surface?: string | null;
    ink?: string | null;
    heroTone?: ('warm' | 'calm' | 'bold') | null;
  };
  seoDescription?: string | null;
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline: string;
            body?: string | null;
            primaryLabel?: string | null;
            primaryHref?: string | null;
            secondaryLabel?: string | null;
            secondaryHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title: string;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'copy';
          }
        | {
            title: string;
            intro?: string | null;
            items?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureList';
          }
        | {
            title: string;
            intro?: string | null;
            items?:
              | {
                  name: string;
                  role?: string | null;
                  quote: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            title: string;
            intro?: string | null;
            leaders: (number | Person)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'leaderCards';
          }
        | {
            title: string;
            body?: string | null;
            formType:
              | 'join-group'
              | 'start-course'
              | 'plan-visit'
              | 'volunteer-interest'
              | 'contact-team'
              | 'external-link';
            buttonLabel: string;
            buttonHref: string;
            emailDestination?: string | null;
            helperText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'signupForm';
          }
        | {
            title: string;
            body?: string | null;
            label: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            title: string;
            questions?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            title: string;
            intro?: string | null;
            feedType: 'groups' | 'courses' | 'events' | 'sermons';
            scope: 'church' | 'ministry';
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relatedFeed';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries".
 */
export interface Ministry {
  id: number;
  church: number | Church;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  audience: string;
  schedule: string;
  featured?: boolean | null;
  summary: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  church: number | Church;
  ministry?: (number | null) | Ministry;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  groupType: 'small-group' | 'sunday-school' | 'bible-study' | 'support-group' | 'serving-team' | 'training-cohort';
  audience: string;
  schedule: string;
  location?: string | null;
  openEnrollment?: boolean | null;
  featured?: boolean | null;
  capacity?: number | null;
  leaders?: (number | Person)[] | null;
  summary: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  church: number | Church;
  ministry?: (number | null) | Ministry;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  courseType: 'new-member' | 'volunteer-training' | 'discipleship' | 'leadership' | 'bible-study' | 'curriculum';
  deliveryMode: 'self-paced' | 'group-led' | 'cohort' | 'hybrid';
  audience: string;
  duration: string;
  featured?: boolean | null;
  certificateOffered?: boolean | null;
  summary: string;
  lessons?:
    | {
        title: string;
        summary: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        resource?: (number | null) | Media;
        estimatedMinutes?: number | null;
        required?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "group-memberships".
 */
export interface GroupMembership {
  id: number;
  church: number | Church;
  group: number | Group;
  person: number | Person;
  role: 'member' | 'leader' | 'apprentice' | 'host';
  status: 'interested' | 'pending' | 'active' | 'paused' | 'completed';
  joinedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "group-sessions".
 */
export interface GroupSession {
  id: number;
  church: number | Church;
  group: number | Group;
  title: string;
  sessionDate: string;
  location?: string | null;
  topic?: string | null;
  attendanceStatus: 'planned' | 'submitted';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance-records".
 */
export interface AttendanceRecord {
  id: number;
  church: number | Church;
  group: number | Group;
  session: number | GroupSession;
  person: number | Person;
  status: 'present' | 'absent' | 'excused' | 'serving';
  checkedInAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-enrollments".
 */
export interface CourseEnrollment {
  id: number;
  church: number | Church;
  course: number | Course;
  person?: (number | null) | Person;
  group?: (number | null) | Group;
  status: 'invited' | 'active' | 'completed' | 'archived';
  progressPercent: number;
  startedAt?: string | null;
  completedAt?: string | null;
  completedLessons?:
    | {
        lessonID: string;
        title: string;
        completedAt: string;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  church: number | Church;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  summary: string;
  startDate: string;
  endDate?: string | null;
  location: string;
  registrationUrl?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons".
 */
export interface Sermon {
  id: number;
  church: number | Church;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  speaker: string;
  series?: string | null;
  summary: string;
  videoUrl?: string | null;
  preachedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities".
 */
export interface Facility {
  id: number;
  church: number | Church;
  name: string;
  roomType: 'sanctuary' | 'classroom' | 'lobby' | 'office' | 'multipurpose';
  capacity: number;
  availability: 'available' | 'reserved' | 'maintenance';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contributions".
 */
export interface Contribution {
  id: number;
  church: number | Church;
  person?: (number | null) | Person;
  donorName: string;
  amount: number;
  fund: 'general' | 'missions' | 'benevolence' | 'building';
  paymentMethod: 'card' | 'ach' | 'cash' | 'check';
  status: 'pending' | 'succeeded' | 'refunded';
  recurring?: boolean | null;
  donatedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'churches';
        value: number | Church;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'ministries';
        value: number | Ministry;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'group-memberships';
        value: number | GroupMembership;
      } | null)
    | ({
        relationTo: 'group-sessions';
        value: number | GroupSession;
      } | null)
    | ({
        relationTo: 'attendance-records';
        value: number | AttendanceRecord;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'course-enrollments';
        value: number | CourseEnrollment;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'sermons';
        value: number | Sermon;
      } | null)
    | ({
        relationTo: 'facilities';
        value: number | Facility;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'contributions';
        value: number | Contribution;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  roles?: T;
  churches?: T;
  person?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  church?: T;
  resourceType?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "churches_select".
 */
export interface ChurchesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  tagline?: T;
  summary?: T;
  heroImage?: T;
  serviceTimes?:
    | T
    | {
        label?: T;
        day?: T;
        time?: T;
        id?: T;
      };
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        postalCode?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        website?: T;
      };
  givingUrl?: T;
  livestreamUrl?: T;
  theme?:
    | T
    | {
        preset?: T;
        accent?: T;
        surface?: T;
        ink?: T;
        heroTone?: T;
        radius?: T;
        headingFont?: T;
        bodyFont?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  church?: T;
  title?: T;
  slug?: T;
  status?: T;
  pageType?: T;
  ministry?: T;
  group?: T;
  course?: T;
  themeMode?: T;
  themeOverrides?:
    | T
    | {
        accent?: T;
        surface?: T;
        ink?: T;
        heroTone?: T;
      };
  seoDescription?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              body?: T;
              primaryLabel?: T;
              primaryHref?: T;
              secondaryLabel?: T;
              secondaryHref?: T;
              id?: T;
              blockName?: T;
            };
        copy?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        featureList?:
          | T
          | {
              title?: T;
              intro?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              title?: T;
              intro?: T;
              items?:
                | T
                | {
                    name?: T;
                    role?: T;
                    quote?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        leaderCards?:
          | T
          | {
              title?: T;
              intro?: T;
              leaders?: T;
              id?: T;
              blockName?: T;
            };
        signupForm?:
          | T
          | {
              title?: T;
              body?: T;
              formType?: T;
              buttonLabel?: T;
              buttonHref?: T;
              emailDestination?: T;
              helperText?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              body?: T;
              label?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              questions?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        relatedFeed?:
          | T
          | {
              title?: T;
              intro?: T;
              feedType?: T;
              scope?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries_select".
 */
export interface MinistriesSelect<T extends boolean = true> {
  church?: T;
  title?: T;
  slug?: T;
  status?: T;
  audience?: T;
  schedule?: T;
  featured?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  church?: T;
  ministry?: T;
  title?: T;
  slug?: T;
  status?: T;
  groupType?: T;
  audience?: T;
  schedule?: T;
  location?: T;
  openEnrollment?: T;
  featured?: T;
  capacity?: T;
  leaders?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "group-memberships_select".
 */
export interface GroupMembershipsSelect<T extends boolean = true> {
  church?: T;
  group?: T;
  person?: T;
  role?: T;
  status?: T;
  joinedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "group-sessions_select".
 */
export interface GroupSessionsSelect<T extends boolean = true> {
  church?: T;
  group?: T;
  title?: T;
  sessionDate?: T;
  location?: T;
  topic?: T;
  attendanceStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance-records_select".
 */
export interface AttendanceRecordsSelect<T extends boolean = true> {
  church?: T;
  group?: T;
  session?: T;
  person?: T;
  status?: T;
  checkedInAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  church?: T;
  ministry?: T;
  title?: T;
  slug?: T;
  status?: T;
  courseType?: T;
  deliveryMode?: T;
  audience?: T;
  duration?: T;
  featured?: T;
  certificateOffered?: T;
  summary?: T;
  lessons?:
    | T
    | {
        title?: T;
        summary?: T;
        content?: T;
        resource?: T;
        estimatedMinutes?: T;
        required?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-enrollments_select".
 */
export interface CourseEnrollmentsSelect<T extends boolean = true> {
  church?: T;
  course?: T;
  person?: T;
  group?: T;
  status?: T;
  progressPercent?: T;
  startedAt?: T;
  completedAt?: T;
  completedLessons?:
    | T
    | {
        lessonID?: T;
        title?: T;
        completedAt?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  church?: T;
  title?: T;
  slug?: T;
  status?: T;
  summary?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  registrationUrl?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons_select".
 */
export interface SermonsSelect<T extends boolean = true> {
  church?: T;
  title?: T;
  slug?: T;
  status?: T;
  speaker?: T;
  series?: T;
  summary?: T;
  videoUrl?: T;
  preachedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities_select".
 */
export interface FacilitiesSelect<T extends boolean = true> {
  church?: T;
  name?: T;
  roomType?: T;
  capacity?: T;
  availability?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  church?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  householdName?: T;
  membershipStatus?: T;
  volunteerReady?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contributions_select".
 */
export interface ContributionsSelect<T extends boolean = true> {
  church?: T;
  person?: T;
  donorName?: T;
  amount?: T;
  fund?: T;
  paymentMethod?: T;
  status?: T;
  recurring?: T;
  donatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}